let a = 5;
let b = 7;
// console.log('Before swap', 'a=', a, 'b=', b);
let temp = a;
a = b;
b = temp;
// console.log('After swap', 'a=', a, 'b=', b);
let x = 15;
let y = 20;
//console.log('Before swap', 'x=', x, 'y=', y);
x = x + y;
y = x - y;
x = x - y;
//console.log('After swap', 'x=', x, 'y=', y);
let p = 8;
let q = 12;
console.log('Before swap', 'p=', p, 'q=', q);
[p, q] = [q, p];
console.log('After swap', 'p=', p, 'q=', q);